### ISSUE TITLE
Most Streams are not playing

### ISSUE THREAD

**Issue by Hiermur** [TomasValenta/WebCams#44]
Hello,

since the second last update (v3.0.1?) most streams will not play on my "Medion LifeTab s10346". There is only a still picture.
With my "Terra Pad 1003" however everything works fine.

Both Tablets works with Android 4.4.

Perhaps there is a problem with the Intel Atom Z3735F (x86) SoC?

Best regards,
Hiermur

**Comment by TomasValenta** [comment]
Hi Hiermur,

I think, you are right. I use for decoding live streams the latest libVLC builds and this library is right now under high development. But in any case x86 is not supported, because I builded the library only for armeabi-v7a.
We will see in the new libVLC versions what will happen or I can think about the multi arch build ;)

**Comment by TomasValenta** [comment]
Hello again,

I have compiled the libVLC also for x86 architecture and I have added multiple productFlavors to build.gradle. Please try the new version 3.0.4 from Play Store (can be visible maybe in next 3 hours). I uploaded both architectures and Play Store will auto select the right type for you cpu. So please give me later a feedback, thank you ;)

**Comment by Hiermur** [comment]
Thank You. Unfortunately, the streams affected not play :-(

**Comment by TomasValenta** [comment]
Can you try to uninstall the installed version and manually install this?
https://github.com/TomasValenta/WebCamViewer/releases/download/3.0.4/app-x86-release.apk

**Comment by Hiermur** [comment]
I can try it in the evening.
How can i backup my sorting and categories.
Root access is available.

**Comment by TomasValenta** [comment]
Categories and sorting is possible only with external backup tool like Titanium Backup, which can backup the whole local db and settings.

**Comment by Hiermur** [comment]
Thanks for the info to save the db with titanium backup :-) I didn't know that it can save the db. 
But, sry,  its the same with manually installation and cam-web-import :(

**Comment by TomasValenta** [comment]
Ok,
thank you for testing it. I can try to report this on official VLC forum. Stay tuned.

**Comment by TomasValenta** [comment]
Reported: https://forum.videolan.org/viewtopic.php?f=32&t=127591

**Comment by Hiermur** [comment]
How can i create some logs for you?

**Comment by TomasValenta** [comment]
You can use application like this:
https://play.google.com/store/apps/details?id=com.tortel.syslog
and send me the logs ;)

**Comment by Hiermur** [comment]
Hope it helps... 

----- Originale Nachricht -----
Von: "Tomáš Valenta" <notifications@github.com>
Gesendet: 30.07.2015 - 23:58
An: TomasValenta/WebCamViewer <WebCamViewer@noreply.github.com>
Betreff: Re: [WebCamViewer] Most Streams are not playing (#44)

**Comment by Hiermur** [comment]
Have you received the attachment?

**Comment by TomasValenta** [comment]
No,
please send me the attachment to my email address:
cz840311 at gmail dot com ;)

**Comment by TomasValenta** [comment]
Hello Hiermur,

thank you for the new logs. Right now I released and uploaded to the Google Play new version with better HW error handling and the new libVLC. Can you please test it on your device?

**Comment by Hiermur** [comment]
Sry, it's the same as with 3.0.4...

**Comment by TomasValenta** [comment]
Ok,

so now we need only to wait for stable libVLC release, because I don't have more ideas :( Sorry for that...

**Comment by Hiermur** [comment]
Hello, 

can you compile the app without hw acceleration for a test? 

Because VLC works better on my device when I deactivate the acceleration.

**Comment by TomasValenta** [comment]
Yes,

try it, here is: http://yetanotherview.cz/tmp/app-x86-release-no-HW.apk

**Comment by Hiermur** [comment]
This version works fine! 

The start behaviour is the same as with 3.0.1 (little artefacts when the streams starts playing).

**Comment by TomasValenta** [comment]
Ok,

thank you for the idea. So we need to wait for fully working HW decoding on devices like your. So every time, when I release new version, I can create for you this customized build  ;)

**Comment by Hiermur** [comment]
Ok. Thank you very much!

**Comment by TomasValenta** [comment]
You are welcome!

I have now better idea with this, I can create possibility to enable or disable HW acceleration in settings ;) I think, it's can be better also for other users with the same issue ;)

**Comment by Hiermur** [comment]
Sounds good ;) 

In earlier builds the app remembered the last category at the start. Is it possible to enable this again?

**Comment by TomasValenta** [comment]
Yes,

I can the possibility also to settings ;)

**Comment by TomasValenta** [comment]
Right now I released a new version with requested features, can you please test it?

**Comment by Hiermur** [comment]
Works fine - thank you :-)

**Comment by TomasValenta** [comment]
Thank you too, nice to hear this! Have nice day ;-)

**Comment by Hiermur** [comment]
You are welcome.
One suggestion I have: it would be nice if it would be possible,  by sorting the cams,  to move them at the  top or bottom with separate buttons. Or by long pressing up/down?

**Comment by TomasValenta** [comment]
I think, it's possible. I can look at this in next days, but in the future I will add to the recyclerview full "drag and drop" feature, but now I don't have so much time...
