### ISSUE TITLE
F-Droid app description

### ISSUE THREAD

**Issue by TomasValenta** [TomasValenta/WebCams#47]
Hello @krt16s,

is possible to fix/update the app description on F-Droid? Streaming video is supported ;)

**Comment by krt16s** [comment]
Sure, see  https://gitlab.com/fdroid/fdroiddata/commit/d9a2cd498cb6790d3ab8b0b19f1782db2faf630e.

**Comment by TomasValenta** [comment]
Thank you Boris!
