### ISSUE TITLE
Feature Request: Widget Auto-Refresh, Fullscreen

### ISSUE THREAD

**Issue by BlueStar88** [TomasValenta/WebCams#49]
I use some cams of Nova Scotia in widget mode. Each widget shows a refresh button below. I suggest following changes:

a) Make an (optional) auto-refresh mode, so stream-like updates are possible. Many cams feed updates constantly. Such a "video" like mode would be a big plus for that widged/app. For battery saving this continuous mode could be linked to the actual visibility (screen with widget in view or not) and device sleep mode.

b) The refresh button is a waste of space. A (manual) refresh could be triggered on tapping the picture itself. Because of the much larger tap area, you won't miss the refresh bar any more.

c) As alternative to b) a picture tap could trigger fullscreen mode.

Thanks for the great work!

Best regards!

BlueStar88

**Comment by TomasValenta** [comment]
B and C variant finished ;) Today I want to try make also "A" variant, but work on Widgets is very limited and frustrating ;)

**Comment by TomasValenta** [comment]
Released! Please test it, thank you ;)

**Comment by BlueStar88** [comment]
Just tested. Option your implementation a) allows a minimum refresh rate of 1 minute. The idea was to support continuous ("stream-like") refreshing (maybe using a 500 ms to 1 second refresh rate). Many cams give a new image, if you hammer manual refresh continuously. So why not making use of it, while the widged containing screen is in view and standby mode is absent?

**Comment by TomasValenta** [comment]
Normally with the parameter **updatePeriodMillis** is minimum refresh interval 30 minutes. With **Alarm manager** was the value from 0 to unlimited. But now from API 22 and up you can see here:
![info](https://cloud.githubusercontent.com/assets/4901251/11612658/6aca1ac0-9c35-11e5-9a45-14feee1587f8.png)

But I think, globaly for the webcameras providers everything less than minute is very bad for their overload. I try now to implement Webcams.travel api and their politics is very strict to server load. So one minute as minimum inteval is, I think, good compromise for both sides. For example, the developers from Webcams.travel refreshing their shots only one time per hour and I understand why...

**Comment by BlueStar88** [comment]
So tell me, why many webcam providers are serving motion jpeg?

To cover overload or battery drain, we could rely on having only smaller time frames, where the user actually looks at those widgets. If those widgets on a hidden screen or the device is sleeping, no refreshing is needed at all. So we are not really talking about constant server loads.

The idea is, to have the beautiful experience of a real time video for some seconds.

Another option to avoid server load would be, to limit the video show to a minute, each time the widget comes into the users view. This will ensure nobody can hog the server(s) for a longer time.

**Comment by BlueStar88** [comment]
http://www.earthcam.com/usa/newyork/timessquare/?cam=tsrobo3

Realtime video is no problem at all these days, it's just the next evolutionary step, having all that bandwidth and powerful servers.

**Comment by BlueStar88** [comment]
So, if a webcam provider delivers motion jpeg, the user is allowed to use it.

Althought there could be mentioned measures for the good of both sides.

**Comment by BlueStar88** [comment]
https://www.cs.dal.ca/webcams/university

Another example. Even a second refresh rate gives a better eperience.

**Comment by BlueStar88** [comment]
http://www.novascotiawebcams.com/en/webcams/museum-wharves/

This one has the same one second rate, but with a very nice blend over effect.
