### ISSUE TITLE
App crashes after update from 3.0.6 to beta4

### ISSUE THREAD

**Issue by Hiermur** [TomasValenta/WebCams#51]

**Comment by Hiermur** [comment]
Hello! 

Clean install is ok. 

Bug or feature? :-) 

Best regards, Hiermur

**Comment by TomasValenta** [comment]
I will, try. Thank you for your report ;)

**Comment by TomasValenta** [comment]
Bug fixed! Next binary release with this fix will be tomorrow ;)

**Comment by Hiermur** [comment]
Thank you :-) 

----- Originale Nachricht -----
Von: "Tomáš Valenta" <notifications@github.com>
Gesendet: 18.11.2015 - 12:19
An: TomasValenta/WebCams <WebCams@noreply.github.com>
Betreff: Re: [WebCams] App crashes after update from 3.0.6 to beta4 (#51)

**Comment by TomasValenta** [comment]
Rc1 released! Please try to to test it again from 3.0.6 to 4.0 rc1 ;)
