### ISSUE TITLE
[FDroid] Future of this app?

### ISSUE THREAD

**Issue by TomasValenta** [TomasValenta/WebCams#53]
Hello @krt16s,

I want to ask you about future of this app in your repository. App is still open source (only access to the database not) and also I need to use some services from Google GMS. So, how we can do that in the future? Can you use in your repository the compiled binaries from GitHub and keep this line in description:
**This app currently uses prebuilt binaries from the author.**
or you need to delete it from your repository completely?

Best Regards,
Tomáš Valenta

**Comment by krt16s** [comment]
We cannot build those two play-service (-location and -maps) libraries. It was okay for known-to-be-opensource lib, but not for play-services which are proprietary, non-free software. If you cannot use a floss-alternative to provide that functionality or the functioanlity is so essential, that you cannot provide a pure-floss build flavour with these features  removed, I really think we are out of luck. There has been a codedrop open-sourcing some services, but I haven't actually looked at it so it might be completly unrelated to gms, see https://android.googlesource.com/platform/tools/studio/google/services/ .

**Comment by TomasValenta** [comment]
GMS libraries is only one part of this, I included also Google in-app donation's and the main problem is with access to the database. From now, if you compile the code from GitHub, you have only demo access. I don't want to make public access to the community database any more, because some people's simply stealing from it and making money on ad's in their applications. So I switched also to the GMS map and location services, because they work much better than open source alternatives. I spend lot of time to make same functionality, but is not the same. It is like cheaper alternative from China. So sorry for that.

**Comment by TomasValenta** [comment]
So,

if is not possible to keep in your repository only the attached apk from GitHub with link to the source code and message:
**This app currently uses prebuilt binaries from the author.**
, then please delete the WebCams from F-Droid repo, because the old version is not working any more.

Thank you Boris
