### ISSUE TITLE
4.0.3 / widget does not respect horizontal width of the original image

### ISSUE THREAD

**Issue by BlueStar88** [TomasValenta/WebCams#56]
![screenshot_2015-12-03-14-36-21](https://cloud.githubusercontent.com/assets/673939/11562596/33e9a45c-99cf-11e5-9538-5c337b770c1e.png)
![screenshot_2015-12-03-14-36-46-1](https://cloud.githubusercontent.com/assets/673939/11562600/38006db4-99cf-11e5-872e-40d858f4d81a.png)

**Comment by BlueStar88** [comment]
![screenshot_2015-12-03-15-09-52-1](https://cloud.githubusercontent.com/assets/673939/11562749/3cb385ac-99d0-11e5-9aef-6be923e3c92e.png)

**Comment by TomasValenta** [comment]
Sorry, I don't understand where is the problem? ;) The image is set to centerCrop, to not have a black borders in the AppWidget ;)

**Comment by TomasValenta** [comment]
And please give a try to the [new version 4.0.4](https://github.com/TomasValenta/WebCams/releases/latest), contain new AppWidget improvements ;)

**Comment by BlueStar88** [comment]
First image shows full size. Second image shows widget mode. As you can see, the image is cropped in both dimensions, vertically and horizontally. There are missed parts in every direction. The result is a zoomed image.
The old behavior was to crop only one dimension, if nescessary, but leave the other at its maximum. So you have at least one dimension scaled losslessly, respecting the aspect ratio and crop the other dimension, so we have no black bars.

**Comment by BlueStar88** [comment]
Third image shows, there will be never a full original width image, regardless how the window is set vertically.

**Comment by BlueStar88** [comment]
In some regard the widged image isn't scaled at all. It's just positioned differently it seems.

**Comment by TomasValenta** [comment]
Give me please time for this, thank you ;)

**Comment by TomasValenta** [comment]
Bug fixed, wait please for the upcoming release ;)

**Comment by TomasValenta** [comment]
Released! You can download latest version here:
https://github.com/TomasValenta/WebCams/releases/latest
