### ISSUE TITLE
Widged misses webcam updates

### ISSUE THREAD

**Issue by BlueStar88** [TomasValenta/WebCams#84]
Some Webcams are not up to date.

See Attachment.
![novascotiamckaybridge01](https://cloud.githubusercontent.com/assets/673939/14018390/d97fb324-f1cd-11e5-9289-723d4b3f11b7.jpg)
![novascotiamckaybridge02](https://cloud.githubusercontent.com/assets/673939/14018393/ddd95452-f1cd-11e5-95a4-79b3aece946b.jpg)
![novascotiamckaybridge03](https://cloud.githubusercontent.com/assets/673939/14018401/e1cdd88a-f1cd-11e5-8f47-acfe3279f7f5.jpg)

**Comment by BlueStar88** [comment]
The hit of update button has no effect on the image, except the circling update icon for a second.

**Comment by BlueStar88** [comment]
My believe is, you operate a caching server, on which the app depends on. Having such a caching mechanism offers its bad side here. We have an additional point of failure and unsolvable strict dependency. Means: Is the server down, the app is worthless. Correct me, if I'm wrong.

**Comment by TomasValenta** [comment]
Hello BlueStar,

I think, that the problem is coming from different side. The image of this WebCam type is not cached, is  directly downloaded from the provider's server. I think, that the problem is maybe coming from memory management in your device. Do you have any "Automatic memory managers"? Can you re-add the widget to the desktop and do not kill the main app from task stack? How much free RAM you have in your device?

Thank you

**Comment by BlueStar88** [comment]
Yes, you are right. The problem is the office network environment I was in. There's a proxy cache system in place. Is your app doing the HTTP-requests using the "Cache-Control: no-cache" option [1]?


[1] https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields

**Comment by TomasValenta** [comment]
Yes, this can be the problem, I have same experience on some places... I can test this parameter, thank you ;)

**Comment by BlueStar88** [comment]
Okay, my assumption is verified:

---
1458899866.338     44 10.6.2.6 **TCP_MEM**_HIT/200 64688 GET http://images.novascotiawebcams.com/mackaybridge/current.jpg - HIER_NONE/- image/jpeg
---

This is a snipped from the proxy server log file. It shows the delivery of the _cached_ image, which is obviously bad in this use case of course. ;-)

**Comment by TomasValenta** [comment]
If you can, please test this version:
http://www.yetanotherview.cz/tmp/app-armv7a-release.apk
it has HTTP-request: Cache-Control: no-cache enabled.

Thank you

**Comment by BlueStar88** [comment]
Yes, it worked, great!

1458923547.181    193 10.6.2.6 **TCP_CLIENT_REFRESH**_MISS/200 18899 GET http://images.novascotiawebcams.com/mackaybridge/current.jpg - HIER_DIRECT/174.142.68.184 image/jpeg

Every hit on that update button gets a new image now.

**Comment by BlueStar88** [comment]
Thank you for the fast fix, btw. ;-)

**Comment by TomasValenta** [comment]
You are welcome. Nice to hear it! ;)
